### ISSUE TITLE
I get this quite often on start

### ISSUE THREAD

**Issue by Geniusssmit** [eshapard/AnkiHabitica#100]
Any help?

```Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-24 11:29:02

Caught exception:
Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1230, in request
  File "http\client.py", line 1276, in _send_request
  File "http\client.py", line 1225, in endheaders
  File "http\client.py", line 1004, in _send_output
  File "http\client.py", line 944, in send
  File "http\client.py", line 1392, in connect
  File "http\client.py", line 915, in connect
  File "socket.py", line 787, in create_connection
  File "socket.py", line 914, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\main.py", line 245, in onOpenProfile
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-54>", line 2, in loadProfile
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 525, in repl
  File "aqt\main.py", line 365, in loadProfile
  File "aqt\gui_hooks.py", line 648, in __call__
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 711, in grab_profile
    if ah.user_settings["check_db_on_profile_load"] and ah.settings.configured and ah.habitica.grab_scorecounter() and compare_score_to_db():
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 364, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\PAUL\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>```

**Comment by 71e6fd52** [comment]
Can you open habitica in your browser?

**Comment by Geniusssmit** [comment]
> Can you open habitica in your browser?

What do you mean? I use it everyday

**Comment by 71e6fd52** [comment]
This error can only be caused by a network error, more specifically DNS related.
