### ISSUE TITLE
Error opening. Does the plugin take effect?

### ISSUE THREAD

**Issue by Lute-Li** [eshapard/AnkiHabitica#102]
Exception ignored in thread started by: <bound method Habitica.check_anki_habit_task of <1758045507.habitica_class.Habitica object at 0x000002033D0F8670>>
Traceback (most recent call last):
  File "C:\Users\gagaga\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 293, in check_anki_habit_task
    out = self.grab_scorecounter()
  File "C:\Users\gagaga\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 364, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\gagaga\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\gagaga\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1321, in do_open
  File "http\client.py", line 1322, in getresponse
  File "http\client.py", line 303, in begin
  File "http\client.py", line 264, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by Lute-Li** [comment]
I successfully created a habit in habitica. 
But when anki is turned on, the plugin will report an error.

**Comment by 71e6fd52** [comment]
Your connection to Habitica is poor. Try using a proxy or something like.
