### ISSUE TITLE
The read operation timed out

### ISSUE THREAD

**Issue by kunpeng9** [eshapard/AnkiHabitica#108]
不知道和啥插件冲突了；关闭了一些后来，没问题了；I don't know what plug-ins conflict with; I closed some later, no problem;
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-15 18:05:02

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 286, in onOpenProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 2033, in __call__
  File "anki\hooks.py", line 583, in runHook
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 748, in grab_profile
    check_unsynced_score()
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 707, in check_unsynced_score
    if not (be_ready() and ah.user_settings["check_db_on_profile_load"] and ah.habitica.grab_scorecounter() and compare_score_to_db()):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 367, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1321, in do_open
  File "http\client.py", line 1322, in getresponse
  File "http\client.py", line 303, in begin
  File "http\client.py", line 264, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out
=

**Comment by 71e6fd52** [comment]
This is a network problem. Consider using a proxy, sometimes Habitica API can't be accessed in mainland China.
