### ISSUE TITLE
Keep getting error (Anki 2.1.22)

### ISSUE THREAD

**Issue by MetalFir** [eshapard/AnkiHabitica#109]
I love this add-on but ever since I downgraded my Anki it has not worked 😢

When loading '⁨Anki Habitica for 21⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 208, in loadAddons
  File "/Users/xxxxxxxx/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 729, in <module>
    gui_hooks.sync_did_finish.append(check_unsynced_score)
AttributeError: module 'aqt.gui_hooks' has no attribute 'sync_did_finish'
⁩

**Comment by Mansonum** [comment]
I have exactly the same issue!  Please inform us how to debug this!

**Comment by Mansonum** [comment]
This bug rears its ugly head since Anki auto checked and installed the new version of this addon. I Use Anki 2.1.26.

**Comment by Mansonum** [comment]
Here I found a temporary workaround. Just put back the deleted addon from the system trashcan after deleting the updated version of addon and restarting anki. This works fine for me.

**Comment by MetalFir** [comment]
I deleted the original add-on a long time ago unfortunately. cleared my trash can 🙁

> Here I found a temporary workaround. Just put back the deleted addon from the system trashcan after deleting the updated version of addon and restarting anki. This works fine for me.

**Comment by Mansonum** [comment]
> I deleted the original add-on a long time ago, unfortunately. cleared my trash can 🙁
> 
> > Here I found a temporary workaround. Just put back the deleted addon from the system trashcan after deleting the updated version of addon and restarting anki. This works fine for me.

Well, I suggest you trying to reach out to the author for the history version of the addon. 😊

**Comment by Blauelf** [comment]
Previous versions of the AnkiHabitica addon (at least the version for Anki 2.1.x) should still be available in the [release section of this GitHub repository](https://github.com/eshapard/AnkiHabitica/releases).

**Comment by MetalFir** [comment]
When I download older versions I keep getting this error message. Oddly it says add-ons possibly involved: ⁨**when is next learning card due today due, Review Heatmap⁩**  even though I know is Habitica causing the problems.



Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-21 22:11:37
Add-ons possibly involved: ⁨when is next learning card due today due, Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-150>", line 2, in _linkHandler
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 69, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-92>", line 2, in _linkHandler
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/matthew/Library/Application Support/Anki2/addons21/563204849/__init__.py", line 138, in myLinkHandler
    return _old(self, url)
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 588, in moveToState
  File "aqt/main.py", line 619, in _reviewState
  File "aqt/reviewer.py", line 55, in show
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-114>", line 2, in wrapped
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 660, in repl
TypeError: hrpg_realtime() takes from 0 to 1 positional arguments but 2 were given

😭

**Comment by MetalFir** [comment]
> I love this add-on but ever since I downgraded my Anki it has not worked 😢
> 
> When loading '⁨Anki Habitica for 21⁩':
> ⁨Traceback (most recent call last):
> File "aqt/addons.py", line 208, in loadAddons
> File "/Users/xxxxxxxx/Library/Application Support/Anki2/addons21/1758045507/**init**.py", line 729, in 
> gui_hooks.sync_did_finish.append(check_unsynced_score)
> AttributeError: module 'aqt.gui_hooks' has no attribute 'sync_did_finish'
> ⁩


For anyone interested it got it to work (I think) 

I just deleted line 729 in the __init__py file 

. in gui_hooks.sync_did_finish.append(check_unsynced_score)

God knows what it does, I don't understand Python 

If anyone can tell me the consequences of deleting that line that would be thankful.

**Comment by 71e6fd52** [comment]
`sync_did_finish` has added since 2.1.34, and I didn't check it. Update either the Anki or the addon can solve it,
