### ISSUE TITLE
crashed after log in habitica ID in windows

### ISSUE THREAD

**Issue by akikaede6** [eshapard/AnkiHabitica#114]
hi, I installed anki  2.1.35 (84dcaa86) in windows, and I try to use habitica add-ons in anki, I copyed 1758045507 to my anki to install this add-on, but when I setup ankihabitica, I copyed my ID and restart anki ,it not worked, and report this request below, 
do I download wrong anki version? Or it's windows ankihabitica bug? My friend use it successfully in linux, with the same anki version.  
```
Error
An error occurred. Please start Anki while holding down the shift key to temporarily disable the plugins you have installed.
If the problem is only caused by the plug-in, please select Tools> Plug-in menu item to set the wrong plug-in as invalid, then restart Anki, repeat the above steps until you find out which plug-in caused the problem.
When you have found that the problem is caused by the plug-in, please check our support site [plug-in support](https: 
Debugging information:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-17 14:52:00

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 53, in handler
  File "aqt\main.py", line 142, in on_window_init
  File "aqt\main.py", line 190, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 231, in setupProfile
  File "aqt\main.py", line 427, in loadProfile
  File "aqt\gui_hooks.py", line 2033, in __call__
  File "lib\site-packages\anki\hooks.py", line 583, in runHook
  File "C:\Users\aki\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 751, in grab_profile
    check_unsynced_score()
  File "C:\Users\aki\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 707, in check_unsynced_score
    if not (be_ready() and ah.user_settings["check_db_on_profile_load"] and ah.habitica.grab_scorecounter() and compare_score_to_db()):
  File "C:\Users\aki\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 367, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\aki\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\aki\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by FirstLoveLife** [comment]
is this error reproducible? can u try to add HTTP_PROXY/HTTPS_PROXY env variable?

**Comment by akikaede6** [comment]
> is this error reproducible? can u try to add HTTP_PROXY/HTTPS_PROXY env variable?

Yes, I have removed this add-on and installed it again, it reported the same error, and i add http_proxy and https_proxy env variable, the same error.

**Comment by 71e6fd52** [comment]
Run setup again and make sure you enter the correct User ID and API Token.

**Comment by akikaede6** [comment]
> Run setup again and make sure you enter the correct User ID and API Token.

I have misunderstood the meaning of API Token, this problem have be sloved, thank you for your reply!
