### ISSUE TITLE
Anki keeps crashing

### ISSUE THREAD

**Issue by enhan226** [eshapard/AnkiHabitica#118]
I get this error:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-11 09:44:05
Add-ons possibly involved: ⁨1758045507⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/taskman.py", line 88, in _on_closures_pending
  File "aqt/taskman.py", line 59, in <lambda>
  File "aqt/taskman.py", line 77, in wrapped_done
  File "aqt/sync.py", line 114, in on_future_done
  File "aqt/main.py", line 913, in on_collection_sync_finished
  File "aqt/hooks_gen.py", line 2912, in __call__
  File "/Users/elizabethnhan/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 707, in check_unsynced_score
  File "/Users/elizabethnhan/Library/Application Support/Anki2/addons21/1758045507/habitica_class.py", line 367, in grab_scorecounter
  File "/Users/elizabethnhan/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 106, in task
  File "/Users/elizabethnhan/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 75, in v3_request
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 640, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by Blauelf** [comment]
Just to be sure, did you set up your ID and access token in Tools >> Ankihabitica >> Setup as described in the installation instructions?

**Comment by 71e6fd52** [comment]
your api token or user id is wrong.
