### ISSUE TITLE
Crash after changing config

### ISSUE THREAD

**Issue by CrashHermit** [eshapard/AnkiHabitica#121]
Anki gives this error after I try to change the config. It doesn't seem to matter what I change in the config, how I change it (via the addon's menu config or I go into the files and edit the config.json), or when (before using the addon or after I've been using it for a bit). The only way to get the addon working again is to disable, uninstall, and reinstall fresh.

Steps to replicate the process:

1. Install addon.
2. Input User ID and API token.
3. Restart Anki.
4. Change settings in the config file.
5. Restart Anki.
6. Error.

`An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-29 10:24:53

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 53, in handler
  File "aqt\main.py", line 142, in on_window_init
  File "aqt\main.py", line 190, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 231, in setupProfile
  File "aqt\main.py", line 413, in loadProfile
  File "aqt\hooks_gen.py", line 2194, in __call__
  File "anki\hooks.py", line 34, in runHook
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 751, in grab_profile
    check_unsynced_score()
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 707, in check_unsynced_score
    if not (be_ready() and ah.user_settings["check_db_on_profile_load"] and ah.habitica.grab_scorecounter() and compare_score_to_db()):
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 315, in compare_score_to_db
    db_score = calculate_db_score(start_date)
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 355, in calculate_db_score
    db_decks = int(db_helper.decks_count(start_date) *
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\db_helper.py", line 163, in decks_count
    cardsDue = [(-nDays, mw.col.db.scalar("""
  File "C:\Users\joshu\AppData\Roaming\Anki2\addons21\1758045507\db_helper.py", line 163, in <listcomp>
    cardsDue = [(-nDays, mw.col.db.scalar("""
  File "anki\dbproxy.py", line 81, in scalar
  File "anki\dbproxy.py", line 60, in _query
  File "anki\_backend\__init__.py", line 60, in db_query
  File "anki\_backend\__init__.py", line 83, in _db_command
anki.errors.StringError: JSONError { info: "data did not match any variant of untagged enum SqlValue" }`

**Comment by 71e6fd52** [comment]
Can't replicate. I have no idea why it happened.

**Comment by MountainsUsual** [comment]
same problems. I am still researching on it.

**Comment by MountainsUsual** [comment]
> same problems. I am still researching on it.

Additionally, I find that the **deckpoints** may be the main cause to this problem. When I set this to default 0 and restart Anki. There are no warning appears.
