### ISSUE TITLE
Error when scoring backlog

### ISSUE THREAD

**Issue by paggarwal24** [eshapard/AnkiHabitica#128]
Hi, whenever I score my backlog after opening Anki I get this error message:

```
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-02-08 15:12:22

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "aqt\taskman.py", line 90, in wrapped_done
  File "aqt\sync.py", line 114, in on_future_done
  File "aqt\main.py", line 965, in on_collection_sync_finished
  File "aqt\hooks_gen.py", line 3771, in __call__
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 725, in check_unsynced_score
    score_backlog()
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 666, in score_backlog
    ah.habitica.post_scorecounter()
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 430, in post_scorecounter
    self.api.update_task(habitID, data)
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 175, in update_task
    out = self.v3_request("put", "/tasks/%s" % task_id, data)
  File "C:\Users\bentu\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

For context, I'm pretty sure that I have the right API key (I tried removing the add-on and installing it again)

**Comment by 71e6fd52** [comment]
You have too many backlogs to score, and reach the limit of Habitica, so I can't do anything on my side. The only way in my view is to ignore the backlog by deleting the existing anki habit.
