### ISSUE TITLE
AnkiHabitica on startup doesn't handle unavailable internet

### ISSUE THREAD

**Issue by richard-hajek** [eshapard/AnkiHabitica#147]
Hey, I got another error, I believe this one is actually cased by AnkiHabitica. This *only* occurs on startup, when internet is not available. It does *not* occur when Anki has already started and a sync was triggered or is quitting and internet is not available.

```bash
Anki 23.12.1 (1a1d4d54) (src) (ao)
Python 3.11.8 Qt 6.7.0 PyQt 6.7.0.dev2404081550
Platform: Linux-6.8.7-arch1-1-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1463, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 956, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/progress.py", line 118, in handler
    func()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 218, in on_window_init
    fn()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 317, in setupProfile
    self.loadProfile()
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 496, in loadProfile
    gui_hooks.profile_did_open()
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 3323, in __call__
    anki.hooks.runHook("profileLoaded")
  File "/usr/lib/python3.11/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/meowxiik/.local/share/Anki2/addons21/1758045507/__init__.py", line 762, in grab_profile
    check_unsynced_score()
  File "/home/meowxiik/.local/share/Anki2/addons21/1758045507/__init__.py", line 718, in check_unsynced_score
    if not (be_ready() and ah.user_settings["check_db_on_profile_load"] and ah.habitica.grab_scorecounter() and compare_score_to_db()):
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meowxiik/.local/share/Anki2/addons21/1758045507/habitica_class.py", line 390, in grab_scorecounter
    response = self.api.task(self.habit_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meowxiik/.local/share/Anki2/addons21/1758045507/habitica_api.py", line 108, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meowxiik/.local/share/Anki2/addons21/1758045507/habitica_api.py", line 77, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2023-12-16T13:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1758045507

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by 71e6fd52** [comment]
This addon heavily relies on a network connection to Habitica, with almost every part of the code making network requests. Therefore, handling situations where the network connection is lost is currently a mess. Additionally, people rarely use their computers without an internet connection, so I don't think this is a serious issue. If you have any ideas for solving this problem, please let me know or make a PR.

**Comment by richard-hajek** [comment]
Fair enough! I'm not really into Anki addons dev right now, but if I have a free moment I'll try and see what can be done!
