### ISSUE TITLE
error pop-up whenever I try to start studying a deck

### ISSUE THREAD

**Issue by shazzy222** [eshapard/AnkiHabitica#148]
this doesn't show up immedietely when I open anki, only when I press the 'study now' button.
Thank you for your help!

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.overview", line 97, in _linkHandler
  File "aqt.main", line 740, in moveToState
  File "aqt.main", line 761, in _reviewState
  File "aqt.reviewer", line 174, in show
  File "aqt.reviewer", line 194, in refresh_if_needed
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\(name)\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 558, in hrpg_realtime
    if compare_score_to_db():
  File "C:\Users\(name)\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 332, in compare_score_to_db
    ah.config[ah.settings.profile]['oldscore'] = ah.config[ah.settings.profile]['score']
KeyError: 'score'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2023-12-16T20:33, 'None', '']
Anki Simulator ['817108664', 2023-11-07T01:26, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-12T22:38, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Progress bar Fixed by Shige ['1708250053', 2024-05-02T09:22, 'None', mod]
ReColor ['688199788', 2024-03-03T09:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', mod]
Straight Reward ['957961234', 2023-11-01T22:11, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1374772155 1708250053 1758045507 1771074083 1908235722 688199788 817108664 957961234

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by 71e6fd52** [comment]
Open the Addon folder by clicking "View File" in the Add-ons dialog box, then try to delete the "user_files" folder in the Anki Habitica addon folder.
