### ISSUE TITLE
anki is freezing up, here is the debug message

### ISSUE THREAD

**Issue by lun4rl1ght** [eshapard/AnkiHabitica#153]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "urllib.request", line 1346, in do_open
  File "http.client", line 1285, in request
  File "http.client", line 1331, in _send_request
  File "http.client", line 1280, in endheaders
  File "http.client", line 1040, in _send_output
  File "http.client", line 980, in send
  File "http.client", line 1447, in connect
  File "http.client", line 946, in connect
  File "socket", line 844, in create_connection
  File "socket", line 832, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.main", line 219, in on_window_init
  File "aqt.main", line 266, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 318, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "_aqt.hooks", line 4107, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users...
  File "C:\Users...init__.py", line 718, in check_unsynced_score
    if not (be_ready() and ah.user_settings["check_db_on_profile_load"] and ah.habitica.grab_scorecounter() and compare_score_to_db()):
  File "C:\Users... line 390, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File..... line 109, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File ... line 78, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib.request", line 517, in open
  File "urllib.request", line 534, in _open
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 1389, in https_open
  File "urllib.request", line 1349, in do_open
urllib.error.URLError: <urlopen error timed out>

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2024-09-03T06:47, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Large and Colorful Buttons ['1829090218', 2018-10-02T13:41, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155 1758045507 1771074083 1829090218

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', mod]

**Comment by yahvk-cuna** [comment]
Make sure your connection to Habitica website is work.
