### ISSUE TITLE
Habitica does not track the progression anymore

### ISSUE THREAD

**Issue by alaraapa** [eshapard/AnkiHabitica#155]
Here is the debug report:

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-13.6.3-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.sync", line 123, in on_future_done
  File "aqt.main", line 1058, in on_collection_sync_finished
  File "_aqt.hooks", line 5038, in __call__
  File "/Users/alara/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 736, in check_unsynced_score
    score_backlog()
  File "/Users/alara/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 676, in score_backlog
    ah.habitica.post_scorecounter()
  File "/Users/alara/Library/Application Support/Anki2/addons21/1758045507/habitica_class.py", line 452, in post_scorecounter
    self.api.update_task(habitID, data)
  File "/Users/alara/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 178, in update_task
    out = self.v3_request("put", "/tasks/%s" % task_id, data)
  File "/Users/alara/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 78, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2999-01-01T03:00, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T17:34, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-10-21T17:29, 'None', mod]
Anki Habitica for 21 ['1758045507', 2024-09-03T13:47, 'None', mod]
AnkiHub ['1322529746', 2024-10-21T20:10, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T18:06, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T10:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']
True Retention ['613684242', 2017-11-19T23:43, 'None', '']
uworld_qid_to_anki_search ['607963104', 2024-04-13T21:56, 'None', '']

===IDs of active AnkiWeb add-ons===
1044112126 1322529746 1374772155 1758045507 1771074083 594329229 607963104 613684242 874215009 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by yahvk-cuna** [comment]
Score Backlog may cause this issue sometimes. I don't have a good way to deal with this problem.
