### ISSUE TITLE
Anki suddenly not starting

### ISSUE THREAD

**Issue by Juneax** [eshapard/AnkiHabitica#158]
Only appears when Habitica is active, turning the others off doesnt help.

Debug Log:

Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.2-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.webview", line 53, in cmd
  File "aqt.webview", line 169, in _onCmd
  File "aqt.webview", line 725, in _onBridgeCmd
  File "aqt.overview", line 98, in _linkHandler
  File "aqt.main", line 770, in moveToState
  File "aqt.main", line 791, in _reviewState
  File "aqt.reviewer", line 183, in show
  File "aqt.reviewer", line 203, in refresh_if_needed
  File "decorator", line 232, in fun
  File "anki.hooks", line 92, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 546, in hrpg_realtime
    if not be_ready():
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 509, in be_ready
    initialize_habitica_class()
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/__init__.py", line 452, in initialize_habitica_class
    ah.habitica = habitica_class.Habitica()
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/habitica_class.py", line 58, in __init__
    self.init_update()  # check habits, grab user object, get avatar
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/habitica_class.py", line 67, in init_update
    self.check_anki_habit()
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/habitica_class.py", line 241, in check_anki_habit
    tasks = self.api.tasks()
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 101, in tasks
    out = self.v3_request("get", "/tasks/user")
  File "/Users/julian/Library/Application Support/Anki2/addons21/1758045507/habitica_api.py", line 78, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2024-09-03T12:47, 'None', mod]
Audiovisual Feedback ['231569866', 2023-07-09T05:34, '0.8', mod]
Pomodium - The best pomodoroTo-do-list add-on for Anki ['678094152', 2024-12-19T02:38, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1758045507 1771074083 231569866 678094152

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Pokmanki ['1041307953', 2023-12-02T15:32, 'None', '']

**Comment by yahvk-cuna** [comment]
Try running Ankihabitica Setup again

**Comment by Juneax** [comment]
Tried to do that, also tried to reinstall it. After the reinstalltion it doesnt Crash, until I set it up with my API.

**Comment by yahvk-cuna** [comment]
"HTTP Error 401: Unauthorized" in the log indicates that you are not logged in correctly to Habitica. Make sure your User ID and API Token are correct.
