### ISSUE TITLE
No progbar?

### ISSUE THREAD

**Issue by haidbz** [eshapard/AnkiHabitica#22]
The progress bar does not appear. Which is weird, since it did in the beginning and I did no configuration to the file or anything? Here is the error message:
```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 21, in link
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.overview", line 37, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.main", line 388, in moveToState
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.main", line 416, in _reviewState
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 55, in repl
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line 54, in show
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 61, in repl
  File "C:\Users\Anon\Documents\Anki\addons\_Timebox_tooltip.py", line 61, in maNextCard
    self._initWeb()
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line 187, in _initWeb
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line 595, in _bottomHTML
  File "C:\Users\Anon\Documents\Anki\addons\ankihabitica.py", line 755, in my_remaining
    if not ah.settings.hrpg_progbar == "":
AttributeError: class ah_settings has no attribute 'hrpg_progbar'
```

**Comment by eshapard** [comment]
Not sure about this... try re-installing. Sounds like a possible file
corruption.

**Comment by eshapard** [comment]
Is time box tooltip a new add-on? Was it working with ankihabitica before?

**Comment by haidbz** [comment]
I thought so too, didn't help. It really confuses me. The error message is not wrong, though; `ah_settings` does not have that attribute, even in the repository.

Actually, the time box thing might have something to do with it. Can't guess at why, though...

**Comment by haidbz** [comment]
It was the time box tooltip. Thanks for the help!
