### ISSUE TITLE
There's a problem here...

### ISSUE THREAD

**Issue by msllsm** [eshapard/AnkiHabitica#32]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\webview.py", line 152, in _linkHandler
  File "aqt\deckbrowser.py", line 41, in _linkHandler
  File "aqt\deckbrowser.py", line 71, in _selDeck
  File "aqt\main.py", line 726, in onOverview
  File "anki\hooks.py", line 55, in repl
  File "aqt\main.py", line 388, in moveToState
  File "aqt\main.py", line 413, in _overviewState
  File "aqt\overview.py", line 24, in show
  File "aqt\overview.py", line 28, in refresh
  File "aqt\overview.py", line 98, in _renderPage
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\Irene\Documents\Anki\addons\Suggest_Starting_Ease_for_the_decks_options_group.py", line 120, in myTable
    gr = makeEaseWarnerStrings(self.mw)
  File "C:\Users\Irene\Documents\Anki\addons\Suggest_Starting_Ease_for_the_decks_options_group.py", line 100, in makeEaseWarnerStrings
    thisVsAvg = abs(avgGrEase - thisDeckEase)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by msllsm** [comment]
I have been reinstalling this addon in different computer several times but the same problem keep commits. I really anticipates this addon will work so I will be motivated to revise Anki cards. 
Also, thank you for your work on this addon, I think it will really benefits me if it works.

**Comment by twilsonco** [comment]
Hello,

This problem is originating in a different add on, Suggest_Starting_Ease_for_the_decks_options_group. 

A simple solution would be to disable that other add on. Especially since this one is doing so much more for you than just suggest setting for the deck :-)

Tim
