### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Jason19900812** [eshapard/AnkiHabitica#36]
Traceback (most recent call last):
  File "aqt\progress.py", line 69, in handler
  File "aqt\main.py", line 110, in setupProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Jason\AppData\Roaming\Anki2\addons\ankihabitica.py", line 708, in grab_profile
    ah.settings.profile = str(aqt.mw.pm.name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by eshapard** [comment]
did you install from ankiweb, or did you install the version on github?

**Comment by captcrouton** [comment]
Looks like I have a similar problem.  Here's the error anki gave me.

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\progress.py", line 69, in handler
  File "aqt\main.py", line 110, in setupProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\Markus Wolf\AppData\Roaming\Anki2\addons\ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "C:\Users\Markus Wolf\AppData\Roaming\Anki2\addons\AnkiHabitica\habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

I have tried to delete and install this several times.  I love it when it works. But it hasn't for maybe a week now. (Not a programmer)

**Comment by eshapard** [comment]
@captcrouton 

Your error is unrelated to the OP's issue.

Did you happen to delete the habitica habit and re-create it? There seems to be a problem with the habit.

Try deleting the config file 'AnkiHabitica.conf' in the AnkiHabitica folder in your Anki addons folder. Also try deleting the habitica habit (Anki Points).

Restart Anki and setup the addon from the tools menu. It should create the config file again and try to create the habitica habit... give it some time to complete that.

Sometimes people get this error at first because the habit isn't created yet, and they just have to wait until the process finishes in the background; after that no problem. So if you get this error again, just review some cards and see if it seems to work anyway.

If this doesn't work, I'll tell you how to turn on logging. That will give me more info.

**Comment by eshapard** [comment]
I made some changes to the version on github. Hopefully, this will fix the problem.

The addon had trouble saving the avatar image using certain characters, so I changed it to use the habitica user ID instead of the profile name.
