### ISSUE TITLE
Relying on name Python to point to Python2

### ISSUE THREAD

**Issue by julka2010** [eshapard/AnkiHabitica#41]
It seems that you are using Python 2.7 libraries, but use python executable. On Arch Linux, Python 3.6 is the default one, so when I launch Anki with only AnkiHabitica installed I get

    An error occurred in an add-on.
    Please post on the add-on forum:
    https://anki.tenderapp.com/discussions/add-ons

    Traceback (most recent call last):
      File "/usr/share/anki/aqt/addons.py", line 47, in loadAddons
        __import__(file.replace(".py", ""))
      File "/home/*****/.local/share/Anki2/addons21/ankihabitica.py", line 8, in <module>
        import urllib2, os, sys, json, thread
    ModuleNotFoundError: No module named 'urllib2'
    Traceback (most recent call last):
      File "/usr/share/anki/aqt/addons.py", line 52, in loadAddons
        __import__(directory)
      File "/home/*****/.local/share/Anki2/addons21/AnkiHabitica/__init__.py", line 7, in <module>
        __import__(module[:-3], locals(), globals())
    ModuleNotFoundError: No module named 'habitica_class'

**Comment by eshapard** [comment]
I just noticed your addons folder is addons21. Are you running Anki 2.1?

On May 4, 2017 2:55 PM, "julka2010" <notifications@github.com> wrote:

It seems that you are using Python 2.7 libraries, but use python
executable. On Arch Linux, Python 3.6 is the default one, so when I launch
Anki with only AnkiHabitica installed I get

An error occurred in an add-on.
Please post on the add-on forum:https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 47, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/*****/.local/share/Anki2/addons21/ankihabitica.py", line
8, in <module>
    import urllib2, os, sys, json, thread
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 52, in loadAddons
    __import__(directory)
  File "/home/*****/.local/share/Anki2/addons21/AnkiHabitica/__init__.py",
line 7, in <module>
    __import__(module[:-3], locals(), globals())
ModuleNotFoundError: No module named 'habitica_class'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eshapard/AnkiHabitica/issues/41>, or mute the thread

**Comment by julka2010** [comment]
Yes, that was my mistake
