### ISSUE TITLE
Error on installation through Anki Web

### ISSUE THREAD

**Issue by DrewSSP** [eshapard/AnkiHabitica#43]
I get the following error when I try to install the script:

Download failed: Traceback (most recent call last):
  File "aqt/downloader.pyc", line 67, in run
  File "httplib2/__init__.pyc", line 1597, in request
  File "httplib2/__init__.pyc", line 1345, in _request
  File "aqt/sync.pyc", line 467, in _conn_request
  File "httplib2/__init__.pyc", line 1013, in connect
  File "httplib2/__init__.pyc", line 80, in _ssl_wrap_socket
  File "ssl.pyc", line 387, in wrap_socket
  File "ssl.pyc", line 143, in __init__
  File "ssl.pyc", line 305, in do_handshake
SSLError: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol

I'm using Anki 2 on OSX 10.

**Comment by eshapard** [comment]
hmm... never seen that before. Could be an ankiweb issue. For now let's use
the github version.

**Comment by DrewSSP** [comment]
That part worked. You're right, the problem is with whatever Anki Web is distributing.
