### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ghost** [eshapard/AnkiHabitica#56]
Traceback (most recent call last):
  File "aqt/progress.pyc", line 69, in handler
  File "aqt/main.pyc", line 110, in setupProfile
  File "aqt/main.pyc", line 244, in loadProfile
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/bbroush/Library/Application Support/Anki2/addons/ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "/Users/bbroush/Library/Application Support/Anki2/addons/AnkiHabitica/habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

**Comment by linberson** [comment]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/progress.py", line 69, in handler
  File "aqt/main.py", line 110, in setupProfile
  File "aqt/main.py", line 244, in loadProfile
  File "anki/hooks.py", line 26, in runHook
  File "/home/fj/.local/share/Anki2/addons/ankihabitica.py", line 717, in grab_profile
    if ah.settings.check_db_on_profile_load and ah.settings.configured and ah.habitica.grab_scorecounter('Anki Points') and compare_score_to_db():
  File "/home/fj/.local/share/Anki2/addons/AnkiHabitica/habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

Hi, seems I have had the same error message.

**Comment by Blauelf** [comment]
This usually happens when your "Anki Points" habit on Habitica exists, but its description does not contain consistent data (AnkiHabitica uses it for things like time of last sync). You can delete the habit and AnkiHabitica will create a new one.

**Comment by linberson** [comment]
Thank you for your fast reply.
It hasnt happened again so far, I suspect it had something to do with using ankidroid, but I also havent been able to reproduce it.
