### ISSUE TITLE
Pop up error

### ISSUE THREAD

**Issue by dmt001** [eshapard/AnkiHabitica#61]
Every time I try to pass an anki card or doing anything, this error appears:

Traceback (most recent call last):
  File "aqt\webview.py", line 21, in link
  File "aqt\reviewer.py", line 319, in _linkHandler
  File "aqt\reviewer.py", line 252, in _showAnswer
  File "aqt\reviewer.py", line 620, in _showEaseButtons
  File "aqt\reviewer.py", line 668, in _answerButtons
  File "anki\hooks.py", line 61, in repl
  File "C:\Users\USER\AppData\Roaming\Anki2\addons\ir\main.py", line 288, in answerButtonList
    if isIrCard(mw.reviewer.card):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons\ir\util.py", line 17, in isIrCard
    mw.readingManager.settings['modelName'])):
AttributeError: ReadingManager instance has no attribute 'settings'

**Comment by Blauelf** [comment]
Are you sure that is related to AnkiHabitica and not [Incremental Reading](https://github.com/luoliyan/incremental-reading/)?

Does the error change or disappear after removing any of those (just move their files from the plugin directory to a different directory)?

**Comment by eshapard** [comment]
Nothing about that message implicates the ankiHabitica addon.
It seems to be an issue with an addon in the 'ir' subdirectory of your 
addons folder... not sure what that is.

This could be a case of two addons not working well together. Either remove 
ankiHabitica, or remove the other one.

Sorry.
