### ISSUE TITLE
i got an error. please help me

### ISSUE THREAD

**Issue by bipper888** [eshapard/AnkiHabitica#94]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-02-25 17:33:52

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\main.py", line 155, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 192, in setupProfile
  File "aqt\main.py", line 365, in loadProfile
  File "aqt\gui_hooks.py", line 648, in __call__
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 711, in grab_profile
    if ah.user_settings["check_db_on_profile_load"] and ah.settings.configured and ah.habitica.grab_scorecounter() and compare_score_to_db():
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 364, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by 71e6fd52** [comment]
please run setup

**Comment by bipper888** [comment]
@71e6fd52 i run setup but the error still shows up

**Comment by 71e6fd52** [comment]
@bipper888 same error message?

**Comment by bipper888** [comment]
@71e6fd52  yes. the same error. and i can't delete the add on, it said: "debug info: [WinError 124] None: 'C:\\Users\\Admin\\AppData\\Roaming\\Anki2\\addons21\\175804~1"

**Comment by 71e6fd52** [comment]
Is there any possibility that you entered the User ID or API Token incorrectly, such as missing the first character when copying.

**Comment by bipper888** [comment]
No. it couldn't. i have used habitica add on for 2 weeks, and nothing happened until i clicked in "score backlog"

**Comment by 71e6fd52** [comment]
Set `keep_log` to true in config and upload the log which can be found in addon_directory/AnkiHabitica.log

**Comment by bipper888** [comment]
i changed keep_log to true but i don't understand "the log". you mean this :
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-02-29 10:31:08

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\main.py", line 155, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 192, in setupProfile
  File "aqt\main.py", line 365, in loadProfile
  File "aqt\gui_hooks.py", line 648, in __call__
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\__init__.py", line 711, in grab_profile
    if ah.user_settings["check_db_on_profile_load"] and ah.settings.configured and ah.habitica.grab_scorecounter() and compare_score_to_db():
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_class.py", line 364, in grab_scorecounter
    response = self.api.task(self.habit_id)
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 106, in task
    out = self.v3_request("get", "/tasks/%s" % str(task_id))
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\1758045507\habitica_api.py", line 75, in v3_request
    response = json.load(opener.open(req, timeout=timeout))
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by 71e6fd52** [comment]
Is this all? you can attach the log file in comment

**Comment by bipper888** [comment]
there are 5 files AnkiHabitica.log1~5 
- log1
2020-03-01 10:09:48,250 [    MainThread: habitica_class.py:  230 -               check_anki_habit()]    ERROR: End function returning: False
2020-03-01 10:09:48,586 [    MainThread: habitica_class.py:  230 -               check_anki_habit()]    ERROR: End function returning: False
2020-03-01 10:09:48,606 [       Dummy-4: habitica_class.py:  154 -                   update_stats()]    ERROR: End function returning: False
there is nothing in the others, i opened the file by notepad is that ok

**Comment by 71e6fd52** [comment]
Sorry, I forgot you also need to set `debug` to true.

**Comment by bipper888** [comment]
[AnkiHabitica.log](https://github.com/eshapard/AnkiHabitica/files/4271446/AnkiHabitica.log)

**Comment by 71e6fd52** [comment]
You set the User ID and API Token to the same value, is it correct?

**Comment by bipper888** [comment]
ohhhh! right. i set all by the User ID. How can i fix it now?

**Comment by bipper888** [comment]
@71e6fd52 thank for your help and apologize for my carelessness

**Comment by 71e6fd52** [comment]
I'm happy to help.

btw I deleted the log in case your User ID is leaked to others,  you should have masked it before upload.
